<template>
  <b-navbar
    variant="success-1"
    toggleable="md"
    type="dark"
    fixed="top"
  >
    <b-navbar-brand to="/" class="d-flex align-items-center">
      <narwhal :size="`1.5em`" />
      <b-img
        src="/midnight-g5-logo.png"
        width="30"
        height="30"
        alt="g5-logo"
        title="G5 Marketing"
        class="mx-3"
      />
      <h1 class="h1-nav-brand">
        Onboarding
      </h1>
    </b-navbar-brand>
    <!-- Right aligned nav items -->
    <b-navbar-nav class="ml-auto pr-2">
      <b-btn
        link
        href="https://getg5.slack.com/archives/CR01N6NNQ"
        target="_blank"
        class="text-white bg-transparent border-0"
        size="sm"
      >
        <slack-icon v-bind="icon" class="jello-vertical" />
      </b-btn>
      <b-btn
        link
        href="https://opex.g5marketingcloud.com"
        target="_blank"
        class="text-white bg-transparent border-0 mr-2"
        size="sm"
      >
        <octopus v-bind="icon" class="jello-vertical" />
      </b-btn>
      <slot />
    </b-navbar-nav>
  </b-navbar>
</template>

<script>
import Octopus from '~/components/icons/octopus'
import SlackIcon from '~/components/icons/slack'
export default {
  components: {
    Octopus,
    SlackIcon
  },
  data() {
    return {
      icon: {
        size: '1.5em',
        color: '#8dc7cb'
      }
    }
  }
}
</script>

<style>
.h1-nav-brand {
  font-size: 0.9em;
  margin-bottom: 0;
  font-weight: 700;
}
.jello-vertical {
  transform: scale3d(1, 1, 1);
  transform-style: preserve-3d;
  transition: 300ms ease-in-out;
}
.h1-nav-brand:hover .jello-vertical {
  animation: jello-vertical 0.9s ease-in-out 300ms both infinite;
}
/* ----------------------------------------------
 * Generated by Animista on 2020-2-5 9:9:46
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
/**
 * ----------------------------------------
 * animation jello-vertical
 * ----------------------------------------
 */
@keyframes jello-vertical {
  0% {
    transform: scale3d(1, 1, 1);
  }
  30% {
    transform: scale3d(0.75, 1.25, 1);
  }
  40% {
    transform: scale3d(1.25, 0.75, 1);
  }
  50% {
    transform: scale3d(0.85, 1.15, 1);
  }
  65% {
    transform: scale3d(1.05, 0.95, 1);
  }
  75% {
    transform: scale3d(0.95, 1.05, 1);
  }
  100% {
    transform: scale3d(1, 1, 1);
  }
}
</style>
